### ISSUE TITLE
Too many input values error being thrown when trying to run cmd   `$ ./generate.sh stateTransition`

### ISSUE THREAD

**Issue by jjhbk** [iden3/tutorial-examples#4]
eTransition_js/witness_calculator.js:124
		throw new Error(`Too many values for input signal ${k}\n`);
		      ^

Error: Too many values for input signal authClaimMtp

    at /home/jjhbk/coding/ssid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:124:9
    at Array.forEach (<anonymous>)
    at WitnessCalculator._doCalculateWitness (/home/jjhbk/coding/ssid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:111:14)
    at WitnessCalculator.calculateWTNSBin (/home/jjhbk/coding/ssid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:187:20)
    at /home/jjhbk/coding/ssid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/generate_witness.js:15:38

Node.js v18.16.0

**Comment by jjhbk** [comment]
The input file is as follows:


{
  "authClaim": [
    "80551937543569765027552589160822318028",
    "0",
    "5684403871959714060192728071636088327855823698671108038608153503912753273320",
    "17670349019909824092865220859476651078435685768662947129252848014885778706912",
    "1",
    "0",
    "0",
    "0"
  ],
  "authClaimMtp": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "authClaimNonRevMtp": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "authClaimNonRevMtpAuxHi": "0",
  "authClaimNonRevMtpAuxHv": "0",
  "authClaimNonRevMtpNoAux": "1",
  "userID": "19491583230718861816355854536313076071227165548420127380269298765404110848",
  "newUserState": "9260317233636147383798447609996558696699779640036812285295832520418314648154",
  "oldUserState": "17642037567244090990042755769669093775104777833982958863946317372357335651704",
  "isOldStateGenesis": "1",
  "claimsTreeRoot": "11825170923163720869218422277462792265254197036150346627815587275009638639507",
  "revTreeRoot": "0",
  "rootsTreeRoot": "0",
  "signatureR8x": "2315234101470270423629979659745705723879102625519919806306212196152282239290",
  "signatureR8y": "3805456448803186160903390250393682674024173927544342085225107370223428187465",
  "signatureS": "1421789802629605664589941338119055420774026702756862670706032502050354324303",
  "newAuthClaimMtp": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "624233278507428878357699085848690664404693305135111460161897996527773905329",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "newClaimsTreeRoot": "15605996837015988488828167427972797666864357720757806310988783337117715048579",
  "newRevTreeRoot": "0",
  "newRootsTreeRoot": "853872474716026496926182873334452810379870056837044580688332700492992941426"
}
